spring.application.name=nfcwapi

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nfc_db
spring.datasource.username=postgres
spring.datasource.password=secret

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

